### ISSUE TITLE
O que significa %2.f ? 

### ISSUE THREAD

**Issue by KC2016** [diogocortiz/Crash-Course-IA#1]
`nao` seria %.2f? ou 2d?

na ultima celula:
`print("Soma dos Erros ao Quadrado (SSE): %2.f " % np.sum((predicoesCo2 - co2_teste)**2))`

**Comment by diogocortiz** [comment]
Oi Karina, 

Você tem razão. Foi um typo, erro de digitação. 
Não deu pau na execução porque colocar digito antes do . é quando se quer limitar o comprimento. 
d é para valor integral.

Espero ter ajudado. :)

**Comment by diogocortiz** [comment]
Já atualizei o código. Obrigado por avisar!

**Comment by KC2016** [comment]
ok. :) Blz!
