### ISSUE TITLE
[DÚVIDA] Ordem dos parâmetros para o r2_score

### ISSUE THREAD

**Issue by RodrigoPiropo** [diogocortiz/Crash-Course-IA#2]
Olá @diogocortiz !
Em RegressaoLinear/crashcourse_regressão_linear.py ou no notebook...

As validações SSE, MSE, MAE e RMSE usam os parametros na seguinte ordem:
```
(co2_teste, predicoesCo2)
```
Porém notei que esta foi usada na a função **r2_score()**:
```
(predicoesCo2 , co2_teste) 
```

A ordem inversa altera o output... seria essa mesma a ordem correta?

Se sim vou reclamar no scikit learn por me confunfir! haha 😅

**Comment by diogocortiz** [comment]
Olá Rodrigo, 
Na verdade fui eu que te confundi. hahaha

Foi um erro de versão. Tinha mudado para mostrar o alunos que invertendo os parâmetros o resultado seria diferente. A ordem to R2 é valor_real, valor_predição, conforme consta na documentação: 
sklearn.metrics.r2_score(y_true, y_pred, *, sample_weight=None, multioutput='uniform_average')

Já atualizei o código. 
Abs,
